#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
picom -b &
#tap to click
xinput set-prop 11 308 1
#natural scrolling
xinput set-prop 11 316 1

bspc monitor -d 1 2 3 4 5 6 7 8
bspc config focus_follows_pointer true

bspc config border_width         0
bspc config window_gap          12
bspc config focused_border_color  '#fc5d7c'
bspc config normal_border_color  '#2c2e34'

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a steam state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
